### ISSUE TITLE
updating stellarsolver makes Kstars unusable

### ISSUE THREAD

**Issue by airscottdenning** [rlancaste/stellarsolver#100]
In ubuntu 20.04.3 on amd-x64

kstars: error while loading shared libraries: libstellarsolver.so.1: cannot open shared object file: No such file or directory

**Comment by rlancaste** [comment]
libstellarsolver.so.1  Would be incorrect since it is version 2 now.  Did you update KStars too to the latest master?

**Comment by rlancaste** [comment]
If this is from the ppa then I don’t know if it is all updated yet.  We will have to ask Jasem

**Comment by rlancaste** [comment]
This should be fixed now.  Jasem rebuilt the kstars-bleeding in the PPA to use StellarSolver 2.0
