### ISSUE TITLE
Icons are installed to the wrong path

### ISSUE THREAD

**Issue by antonio-rojas** [rlancaste/stellarsolver#102]
The icons are installed in `icons/hicolor/$size/StellarSolverIcon.png`, but they should be in `icons/hicolor/$size/apps/StellarSolverIcon.png` instead. Otherwise KDE and Gnome application menus can't display them, see  https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s07.html

**Comment by rlancaste** [comment]
I don't know anything about that, I can send it to the person who did the icons

**Comment by mattiaverga** [comment]
Yep, shame on me, I've completely forgot the `apps` subdir. I've pushed #103 as a fix

**Comment by rlancaste** [comment]
Thank you very much for the fix.  I just merged it.  Please check that all is well now Antonio.

**Comment by antonio-rojas** [comment]
Thanks!
