### ISSUE TITLE
Commandline stellarsolver client

### ISSUE THREAD

**Issue by gnthibault** [rlancaste/stellarsolver#126]
Dear all,

First of all, thank you soo much for the work on this amazing tool. In my daily development workflow, I am uing solve-field to develop an automated telescope control system. However, I realized the overall solve process was still quite slow. Although with stellarsolver I managed to get ultra-fast solve (at least 2 to 5 times faster).
I would like to use Stellarsolver as I was using solve-field, in commandline although I don't need full set of options, just basics one, similar to astap (use sampling, approximate ra/dec position, radius ).

I know I can develop this by my self, but I haven't written C++ in a while, I'll see if I can provide a pull request for this later. But definitely it feels like a very useful additional application to stellarsolver library.

**Comment by rlancaste** [comment]
Thank you for your comment.  Please note that one of the main goals of stellarsolver was to get away from the command line usage and temporary files and that is one of the reasons that it is faster.  It is an internal library of KStars (and other programs) and not an external program that must be run as a separate process.  The POSIX requirements of astrometry.net were preventing full usage in the native Windows operating system and the temporary files required for its use were not good for Raspberry Pis.  Also running secondary processes hampers full debugging on MacOS.  Making StellarSolver an internal library that involved no command line usage was how I made it work well.   That being said, if someone were to develop a command line interface that still worked on all the different operating systems and did not require a huge amount of temporary files being written, I would certainly not object as long as it doesn't prevent using StellarSolver as an internal library.
