### ISSUE TITLE
how  to build stellarsolver tester  and stellarbatchsolver  with QtCreator ?

### ISSUE THREAD

**Issue by taurushappy** [rlancaste/stellarsolver#133]
I am newer  to Craft , follow the instruction build  on  winodows  ,  already  build stellarsolver ,but don not   known how to build stellarsolver tester  and stellarbatchsolver   ,and  package  stellarsolver tester  and stellarbatchsolver   to .exe file,
can you give me how to do this

**Comment by rlancaste** [comment]
If you are using qt creator to edit and build, there is a checkbox to turn on the options of building those applications in addition to the library.  If you are using craft, you can set the options in the recipe.  In this repo I have modified craft recipes for building those with those options turned on so you can see how it’s done.  If you build from the command line you can turn the options on in the cmake configure step

**Comment by taurushappy** [comment]
thank you  very much,    I use craft  don not  known  how to set the options , can tell how to set  options   to build  stellarsolver

**Comment by taurushappy** [comment]
> If you are using qt creator to edit and build, there is a checkbox to turn on the options of building those applications in addition to the library. If you are using craft, you can set the options in the recipe. In this repo I have modified craft recipes for building those with those options turned on so you can see how it’s done. If you build from the command line you can turn the options on in the cmake configure step

thank you very much ,your reply!   I try the command line is "craft --compile --options BUILD_TESTER=ON stellarsolver"   is right?

**Comment by taurushappy** [comment]
thanks,&nbsp; I finally&nbsp; direct use&nbsp;&nbsp;stellarsolver 's lib&nbsp;&nbsp; libstellarsolver in qt creator
instead of build the stellarsolver source&nbsp;
windows&nbsp; &nbsp;mscv2019 + qt creator 5.15
INCLUDEPATH += D:\qt_projects\astrocamera\libstellarsolver
LIBS += D:\CraftRoot\lib\stellarsolver.lib



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rlancaste/stellarsolver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月25日(星期天) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rlancaste/stellarsolver] how  to build stellarsolver tester  and stellarbatchsolver  with QtCreator ? (Issue #133)





 
I am assuming this worked out for you?  It sounded right.  Please let me know if you need more help.

**Comment by rlancaste** [comment]
Nice, smart!
