### ISSUE TITLE
star  extraction,  how to solver   "internal pixel buffer full "

### ISSUE THREAD

**Issue by taurushappy** [rlancaste/stellarsolver#135]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Star Extractor with the 4-SmallScaleSolving profile . . .
internal pixel buffer full
internal pixel buffer full
internal pixel buffer full
internal pixel buffer full
internal pixel buffer full
internal pixel buffer full
internal pixel buffer full
internal pixel buffer full
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Internal Extractor  success! Got 0 stars
Star Extraction took a total of: 0.119 second(s).
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by rlancaste** [comment]
Hi there,

That is an SEP error, not specifically a StellarSolver issue.  I did an internet search for what could cause this and I came upon this forum discussion: https://github.com/kbarbary/sep/issues/15. Hopefully this is helpful.   Some ideas I have are that you might need to do more background subtraction from the image, or maybe try changing some of the SEP settings in your profile, such as threshold values.  If the image is too big, you could try the partitioning function that Jasem added to StellarSolver to make SEP more efficient.    If you are willing to share the image, I could try some setting changes to see if I can get it to work.

Rob

**Comment by taurushappy** [comment]
thank&nbsp; U&nbsp; ! this is the image&nbsp; &nbsp;I used


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rlancaste/stellarsolver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月21日(星期三) 凌晨5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rlancaste/stellarsolver] star  extraction,  how to solver   "internal pixel buffer full " (Issue #135)





 
Hi there,
 
That is an SEP error, not specifically a StellarSolver issue.  I did an internet search for what could cause this and I came upon this forum discussion: kbarbary/sep#15. Hopefully this is helpful.   Some ideas I have are that you might need to do more background subtraction from the image, or maybe try changing some of the SEP settings in your profile, such as threshold values.  If the image is too big, you could try the partitioning function that Jasem added to StellarSolver to make SEP more efficient.    If you are willing to share the image, I could try some setting changes to see if I can get it to work.
 
Rob
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

IMG_20231208202948_123.jpg (6.21M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=2e3064660caefdce8e89c1474336531e19445153035752554c02535f571b5401055349055154001c575105505d03510104565254652c61782c773b545504520053005c5455045805596f555456180b41063059&t=exs_ftn_download&code=a0dfe6a1




IMG_20231208202948_123.zip (6.18M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=2d3336640542ad9c8d8a93451365024c1a470e050d5301074f000f565348010057011b555353534e015757540c55015b56030e50357f302a2f7469560557035250030e56055709575a6c0756064b4a0a12330b&t=exs_ftn_download&code=b36d5e0c

**Comment by taurushappy** [comment]
thanks&nbsp; very much .&nbsp; deal the&nbsp; problem .
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rlancaste/stellarsolver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月23日(星期五) 凌晨1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rlancaste/stellarsolver] star  extraction,  how to solver   "internal pixel buffer full " (Issue #135)





 
I checked out your image.  It had a lot of noise, the stars and the background are very similar.  You might try doing darks or biases to remove some of that.  You also would improve it by averaging some images to reduce the random error.  I opened it in my stellar solver tester and just started playing with some parameters.  I found that changing the threshold variables (threshold multiple and threshold offset)  did make a difference. Increasing both of those allowed it to find objects and avoid the error.  Adjusting them further helped me get it to circle the stars and not other things.  You will need to carefully tweak the values to get it to find the stars in your image and not the noise.

**Comment by rlancaste** [comment]
Thanks!
