### ISSUE TITLE
Could we have a minor release for the compiler fixes?

### ISSUE THREAD

**Issue by MattBlack85** [rlancaste/stellarsolver#145]
I really prefer to pull from tagged versions when compiling for packaging instead of pulling from branches and/or commits?

**Comment by rlancaste** [comment]
I am hoping to have more of a major release with in the next two weeks or so actually.  I have been working on a big change you can find in the supporting qt6 branch, and that should allow either qt5 or 6.  Right now there is a problem with the qt6 option and partitioning but I hope to either fix that or put a warning on it to not use partitioning on qt6 for now.

**Comment by rlancaste** [comment]
Either way, very soon

**Comment by MattBlack85** [comment]
cool, thanks for the fyi then! closing this and waiting!
