### ISSUE TITLE
StellarSolverTester incorrectly checks available memory

### ISSUE THREAD

**Issue by gilesco** [rlancaste/stellarsolver#17]
On Raspberry Pi4 8GB StellarSolverTester issues the following message:

###

Evaluating Installed RAM for inParallel Option.  Total Size of Index files: 31.7369 GB, Installed RAM: 1.71799e+10 GB
There should be enough RAM to load the indexes in parallel.

###

Of course, it hasn't got that memory available, and, in fact, on the Pi4 8GB, any one process still only has 4GB available to it.

Most options results in a out-of-memory errors and eventually a seg fault.

Similarly, latest build of kstars from Git either fail to solve, or crash kstars when using StellarSolver.

**Comment by rlancaste** [comment]
Ok, I have a Raspberry Pi, I will test this out and see why it computes the amount of memory incorrectly, I can probably do that tomorrow afternoon.

**Comment by gilesco** [comment]
I can confirm this appears to now have been resolved:
Evaluating Installed RAM for inParallel Option.  Total Size of Index files: 31.7369 GB, Installed RAM: 7.64153 GB
Not enough RAM is available on this system for loading the index files you have in parallel
Disabling the inParallel option.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Sextractor. . .
Stars Found before Filtering: 3097
Removing the stars with a/b ratios greater than 1.5
Keeping just the 50 brightest stars
Stars Found after Filtering: 50
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Configuring StellarSolver
Set odds ratio to solve to 1e+09 (log = 20.7233)

Scale range: 2.35182 to 2.87444 arcsec/pixel

Downsampling is multiplying the scale by: 2
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting Internal StellarSolver Astrometry.net based Engine. . .
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Solve Log Odds:  222.518
Number of Matches:  40
Solved with index:  4108
Field center: (RA,Dec) = (38.1603, 62.6568) deg.
Field center: (RA H:M:S, Dec D:M:S) = (02:32:38.463, +62:39:24.581).
Field is: (128.653, 115.819) deg from search coords.
Field size: 1.70109 x 1.28661 degrees
Pixel Scale: 1.31564"
Field rotation angle: up is -138.765 degrees E of N
Field parity: neg

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Internal Sextractor w/ StellarSolver  took a total of: 5.101 second(s).
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
