### ISSUE TITLE
Some C++ files built with C options

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#24]
Example:
```
[ 22%] Building CXX object CMakeFiles/stellarsolver.dir/stellarsolver/sep/lutz.cpp.o
cc1plus: warning: command line option '-Wno-implicit-function-declaration' is valid for C/ObjC but not for C++
```

**Comment by knro** [comment]
yes I've seen this... how can this be enabled just for the C files?

**Comment by gilesco** [comment]
target_compile_options(stellarsolver PRIVATE $<$<COMPILE_LANGUAGE:C>:-Wno-implicit-function-declaration>)
target_compile_options(stellarsolverstatic PRIVATE $<$<COMPILE_LANGUAGE:C>:-Wno-implicit-function-declaration>)

**Comment by rlancaste** [comment]
Thank you very much, please check if this is resolved for you
