### ISSUE TITLE
Resource leak in astrometry/util/scamp.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#29]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/scamp.c#L27-L34

Both `hdr` and `scamp` leak here.

**Comment by rlancaste** [comment]
I did fix a few memory leaks in the astrometry code.  When I told him, Dustin Lang was very surprised that there were any.  We can try to fix it, but I don't want to break it either.

**Comment by rlancaste** [comment]
So you are thinking that inside of the second if statement, we should release those objects?

**Comment by TallFurryMan** [comment]
Yesterday evening I started to have a look at the reports from Coverity. This was a single issue, not necessarily important, that I transferred before being preempted. I'll continue, there a certain number of leaks like this.

The point here that I do not make obvious, is that Dustin is consolidating an executable. As such, this resource leak is completely minor as the process just exits afterwards. If in your case you are consolidating a library than is to be integrated e.g. to KStars, I think all leaks should be resolved.

**Comment by TallFurryMan** [comment]
Whether to fix those here or at Dustin's repository is a good question. Still, you are integrating the code, not referring to it as a submodule for instance, so those issues are relevant here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786313&defectInstanceId=10334135&mergedDefectId=303562
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786313&defectInstanceId=10333995&mergedDefectId=303751

**Comment by rlancaste** [comment]
I think this one is fixed
