### ISSUE TITLE
Resource leak in astrometry/blind/blind.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#30]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/blind/blind.c#L1392-L1398

`hdr` and `fout` are lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786234&defectInstanceId=10334090&mergedDefectId=303715

**Comment by rlancaste** [comment]
I think this one is fixed

**Comment by TallFurryMan** [comment]
Yes, although the next function in the file (`write_scamp_file`) has three more leaks of the same type.
