### ISSUE TITLE
Resource leak in astrometry/blind/verify.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#31]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/blind/verify.c#L86-L89

`vf` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786287&defectInstanceId=10333955&mergedDefectId=303747

**Comment by rlancaste** [comment]
I think this one is fixed

**Comment by TallFurryMan** [comment]
Agreed. Line 804 leaks `starid` as well, same construct. I didn't enter it at first because I thought we were not using the bounding circle feature, I'm not sure anymore if we do, I tend to think we don't.
