### ISSUE TITLE
Resource leak in astrometry/util/wcs-pv2sip.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#32]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/wcs-pv2sip.c#L181-L191

`ct` is overwritten without being freed here.

**Comment by rlancaste** [comment]
I think this one is fixed
