### ISSUE TITLE
Resource leak in astrometry/qfits-an/anqfits.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#34]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/qfits-an/anqfits.c#L546-L557

`fid` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786474&defectInstanceId=10333996&mergedDefectId=303741

**Comment by rlancaste** [comment]
I think this is fixed now

**Comment by TallFurryMan** [comment]
At line 522 in the function preceding this, `str` is left leaking too. Postponing.
