### ISSUE TITLE
Resource leak in astrometry/qfit-an/qfits_image.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#36]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/qfits-an/qfits_image.c#L454-L455

`buf_out`/`op` is lost in that function.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786479&defectInstanceId=10333865&mergedDefectId=303739

**Comment by rlancaste** [comment]
I think this one is fixed

**Comment by TallFurryMan** [comment]
There are other specialized functions in that file: same issue is visible in `qfits_pixdump_int` and `qfits_pixdump_float`. I thought you would take care of them too. Sorry we need to reopen this, as the `double` specialisation is probably not the one KStars is using.
