### ISSUE TITLE
Resource leak in astrometry/blind/solvedfile.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#38]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/blind/solvedfile.c#L245-L249

`vals` is not closed on `fwrite` success, leaking.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786277&defectInstanceId=10333923&mergedDefectId=303734&fileStart=251&fileEnd=304

**Comment by rlancaste** [comment]
I think this is fixed now

**Comment by TallFurryMan** [comment]
Coverity still complains, but this time for the second issue I didn't bother to enter at first: `f` leaks if `fwrite(vals...)` fails.

This malevolent way of assembling return codes is present multiple times in the code. Let's postpone its fix.
