### ISSUE TITLE
Resource leak in astrometry/blind/engine.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#40]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/blind/engine.c#L1055

It seems `path` is overwritten repeatedly, sometimes not initialized properly, in that function. Code is a bit strange, I did not follow all paths :worried:

**Comment by TallFurryMan** [comment]
Situation is similar in `job_set_input_base_dir`.

**Comment by rlancaste** [comment]
I am not sure this one is a resource leak. It looks like if any of these blind parameters are set, it uses the "resolve path" function, gets a new path, prints a message, changes the parameter to the new path and then frees the old one.  As an example:
if (bp->cancelfname) { //If the parameter for the path exists
path = resolve_path(bp->cancelfname, dir); //gets the full path
logverb("Cancel file was %s, changing to %s.\n", bp->cancelfname, path);  //prints out both the old path and new path
free(bp->cancelfname); //Frees the old path
bp->cancelfname = strdup_safe(path); //Sets the parameter to the new path

I think he reuses the pointer, but it doesn't leak

**Comment by TallFurryMan** [comment]
This is the code of `resolve_path`:

https://github.com/rlancaste/stellarsolver/blob/8feed6b7a7d774d313e8fb382e10d40c8bdb2f0b/stellarsolver/astrometry/util/fileutils.c#L15-L31

I believe the scanner got it wrong, but got something serious though. First, `asprintf_safe` is given the uninitialized local `path` as a pointer argument but internally does a `vasprintf` on it. Second, `blind_set_cancel_file` (for instance) does a `strdup_safe` on the structure field, leaving the original (actually unallocated?) resource to leak. This all seems very messy in terms of allocator-owner rules, and incorrect.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786220&defectInstanceId=10333987&mergedDefectId=303730
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786220&defectInstanceId=10334144&mergedDefectId=303731

**Comment by rlancaste** [comment]
Ok these should now be resolved.  I have finally managed to make the code totally internal.  There is no more solved file and no more cancel file.  There is no need for any of this code any more, so I removed it.
