### ISSUE TITLE
Resource leak in astrometry/libkd/kdtree_internal.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#42]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/libkd/kdtree_internal.c#L2411-L2415

Resource leak confirmed by Coverity.

**Comment by rlancaste** [comment]
This one looks very complicated

**Comment by rlancaste** [comment]
I think I fixed this in my last commit, can you check?

**Comment by TallFurryMan** [comment]
I'll review this, and automate the process to get back to you.

**Comment by rlancaste** [comment]
Ok thanks
