### ISSUE TITLE
Resource leak in externalsextractorsolver.cpp

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#43]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/externalsextractorsolver.cpp#L1291-L1296

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/externalsextractorsolver.cpp#L1302-L1306

`xArray`, `magArray` and `yArray` are lost here.

**Comment by rlancaste** [comment]
I think this one is fixed
