### ISSUE TITLE
Resource leak in sep/extract.cpp

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#51]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/sep/extract.cpp#L355-L359

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/sep/extract.cpp#L752

If `conv` is `true`, `cdscan` leaks here.

**Comment by knro** [comment]
I believe this is fixed.

**Comment by TallFurryMan** [comment]
Coverity complains it is not, but probably this is because of the sequence of markers. Postponing, although the issue is real.

**Comment by TallFurryMan** [comment]
As a side note, there are a bunch of uninitialised variables being used in that file, you may want to check the report.
