### ISSUE TITLE
Resource leak in astrometry/util/mathutil.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#53]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/mathutil.c#L383

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/mathutil.c#L412-L415

`F` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786396&defectInstanceId=10333901&mergedDefectId=303588

**Comment by rlancaste** [comment]
I think this one is fixed
