### ISSUE TITLE
Resource leak in astrometry/util/qidxfile.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#54]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/qidxfile.c#L43

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/qidxfile.c#L56-L59

`qf` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786310&defectInstanceId=10333845&mergedDefectId=303665

**Comment by rlancaste** [comment]
I think this one is fixed
