### ISSUE TITLE
Resource leak in astrometry/util/quadfile.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#55]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/quadfile.c#L56

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/quadfile.c#L76-L79

`qf` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786312&defectInstanceId=10334125&mergedDefectId=303660

**Comment by rlancaste** [comment]
I think this one is fixed
