### ISSUE TITLE
Resource leak in astrometry/util/scamp-catalog.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#56]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/scamp-catalog.c#L72-L75

`hdrstring`, `freehdr` and `hdr` are lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786314&defectInstanceId=10334071&mergedDefectId=303548
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786314&defectInstanceId=10334029&mergedDefectId=303632

**Comment by rlancaste** [comment]
I think this one is fixed
