### ISSUE TITLE
Resource leak in astrometry/util/sip_qfits.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#57]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/sip_qfits.c#L88-L91

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/sip_qfits.c#L121-L124

`fid` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786387&defectInstanceId=10334009&mergedDefectId=303551
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786387&defectInstanceId=10333937&mergedDefectId=303603

**Comment by rlancaste** [comment]
I think this one is fixed
