### ISSUE TITLE
Resource leak in astrometry/util/starkd.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#58]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/starkd.c#L408

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/starkd.c#L417

`counts` is lost here.

**Comment by rlancaste** [comment]
I think this one is fixed
