### ISSUE TITLE
Resource leak in astrometry/util/starkd.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#59]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/starkd.c#L559-L562

`io` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786305&defectInstanceId=10333899&mergedDefectId=303558
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786305&defectInstanceId=10334129&mergedDefectId=303655

**Comment by TallFurryMan** [comment]
Also `io` is passed null explicitly to `kdtree_fits_write_tree`, which de-references it unconditionally, in some cases.

**Comment by rlancaste** [comment]
I think this one is fixed
