### ISSUE TITLE
Double free in astrometry/util/multiindex.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#60]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/multiindex.c#L140-L148

`quads` and `fits` are freed twice here. `codes` is not used, its free branch is dead code.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786301&defectInstanceId=10334106&mergedDefectId=303576
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786301&defectInstanceId=10334054&mergedDefectId=303580

**Comment by rlancaste** [comment]
I think this one is fixed
