### ISSUE TITLE
Resource leak in astrometry/util/fitstable.c

### ISSUE THREAD

**Issue by TallFurryMan** [rlancaste/stellarsolver#61]
https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/fitstable.c#L298-L301

`buf` is lost here.

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/fitstable.c#L644-L647

`dest` and `tempdata` are lost here.

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/fitstable.c#L945-L948

`fitsdata` and `cdata` are lost here.

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/fitstable.c#L975-L979

`fitsdata` and `tempdata` are lost here.

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/fitstable.c#L839-L843

`buf` and `src` are lost here.

https://github.com/rlancaste/stellarsolver/blob/e0aa8d394aa9ddd5ad9c1052fff249d019913c49/stellarsolver/astrometry/util/fitstable.c#L1274-L1281

`outtable` is lost here.

**Comment by TallFurryMan** [comment]
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786390&defectInstanceId=10334131&mergedDefectId=303547
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786390&defectInstanceId=10334042&mergedDefectId=303554
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786390&defectInstanceId=10334087&mergedDefectId=303565
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786390&defectInstanceId=10333959&mergedDefectId=303625
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786390&defectInstanceId=10334132&mergedDefectId=303679
https://scan3.coverity.com/reports.htm#v48457/p13483/fileInstanceId=42786390&defectInstanceId=10333894&mergedDefectId=303711

**Comment by rlancaste** [comment]
I think this one is fixed
