### ISSUE TITLE
Build is not possible on Raspberry Pi 64 bit Bullseye

### ISSUE THREAD

**Issue by phomer60** [rlancaste/stellarsolver#94]
I get the following error when installing the prerequisites because I am asked to install obsolete software.

sudo apt -y install git cmake qt5-default libcfitsio-dev libgsl-dev wcslib-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate
Paul

**Comment by rlancaste** [comment]
qt5-default is obsolete??  does everyone have to switch now to qt6?? I don't think that craft or the PPA for kstars are currently using qt6 yet and I know I haven't even tried qt6.  I don't know if that would break anything.

**Comment by phomer60** [comment]
I found a reference online to say it was obsoleted but I do not know how accurate it is.

[https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjfqrS8wPn1AhWyS2wGHZJaC5IQFnoECAQQAQ&url=https%3A%2F%2Faskubuntu.com%2Fquestions%2F1335184%2Fqt5-default-not-in-ubuntu-21-04&usg=AOvVaw3HXli-7M5RXNpcrhRdoJmh](url)

**Comment by knro** [comment]
It's definitely not obsolete. The package was renamed, that's all. qtbase5-dev ..etc

**Comment by rlancaste** [comment]
Ok I will edit the instructions to reflect this change.  Do we know if all machines should use this new package, or is it just a few ubuntu versions?

**Comment by rlancaste** [comment]
Ok I just edited it.
