### ISSUE TITLE
desktop file is missing from repo

### ISSUE THREAD

**Issue by antonio-rojas** [rlancaste/stellarsolver#98]
make install fails when building the tester because it tries to install a non-existant desktop file
```
CMake Error at build/cmake_install.cmake:165 (file):
  file INSTALL cannot find
  "/build/stellarsolver/src/stellarsolver-2.0/tester/com.github.rlancaste.stellarsolver.desktop":
  No such file or directory.
```

**Comment by rlancaste** [comment]
That's weird, I wonder what happened to it.  I will look

**Comment by rlancaste** [comment]
Oh I think I see what happened, that was a contribution from another person about 10 days ago and I think he forgot to include a file, let me message him.

**Comment by rlancaste** [comment]
I just left a message for him on the commit:  https://github.com/rlancaste/stellarsolver/commit/137f1fb121e274ee06de1c9b4dbceabc5719bf16

**Comment by rlancaste** [comment]
Can you check if this is fixed.  He just sent another pull request

**Comment by antonio-rojas** [comment]
make insall is fixed, yes. It still doesn't work properly because the icons are installed to the wrong path, but I'll open a separate report for that.
